version: '3.8'

services:
  postgres:
    image: postgres
    container_name: v6-academy-postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: v6-academy-db
    volumes:
      - data_postgres:/var/lib/postgresql/data
 
  redis:
    image: bitnami/redis
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
      ports:
      - '6379:6379'
      volums:
      - data_redis/bitnami/redis/data
      
volumes:
  data_postgres:



